# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    KAFKA_BOOTSTRAP_SERVERS=kafka:9093 \
    KAFKA_TOPIC=network-packets-ids

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY packet-consumer.py .
COPY trained_model.pkl .

# Expose the Flask port
EXPOSE 5002

# Command to run the consumer script
CMD ["python", "packet-consumer.py"]
